-- CREATE TABLE [dbo].[UserRoles] (
--     [UserId] INT NOT NULL,
--     [RoleId] INT NOT NULL,
--     CONSTRAINT [PK_UserRoles] PRIMARY KEY ([UserId], [RoleId]),
--     FOREIGN KEY ([UserId]) REFERENCES [dbo].[Users]([Id]) ON DELETE CASCADE,
--     FOREIGN KEY ([RoleId]) REFERENCES [dbo].[Roles]([Id]) ON DELETE CASCADE
-- );